version: "3.9"
services:
  server:
    build: 
        context: ./server
        dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
  client:
    build: 
        context: ./client
        dockerfile: Dockerfile.client
    ports:
      - "5000:5000"